import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/Home.module.scss";
import { Card } from "components";
import { ICardProps } from "interfaces";

const Home: NextPage = () => {
  const cards: ICardProps[] = [
    {
      isLink: true,
      link: "/flip-spinner",
      className: styles.card,
      title: "Flip Spinner",
      subtitle: "Animated card flipping around",
    },
    {
      isLink: true,
      link: "/bouncy-loader",
      className: styles.card,
      title: "Bouncy Loader",
      subtitle: "Animated bouncy loader",
    },
    {
      isLink: true,
      link: "/animated-searchbar",
      className: styles.card,
      title: "Animated Search Bar",
      subtitle: "Animated Search Bar",
    },
    {
      isLink: true,
      link: "/progress-bar",
      className: styles.card,
      title: "Progress Bar",
      subtitle: "Animated Progress Bar",
    },
  ];
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          UI Example <span>Codes!</span>
        </h1>

        <p className={styles.description}>
          To get you going as fast as possible...
        </p>

        <div className={styles.grid}>
          {cards.map((card) => (
            <Card
              key={card.link}
              isLink={card.isLink}
              link={card.link}
              className={card.className}
              title={card.title}
              subtitle={card.subtitle}
            />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;
